version: '3'

services:
  #spring-app:
    #image: my-image:latest
    #ports:
      #- "9090:9090"
    #environment:
      #SPRING_DATASOURCE_URL: jdbc:postgresql://192.168.136.132:5432/devops
      #SPRING_DATASOURCE_USERNAME: postgres
      #SPRING_DATASOURCE_PASSWORD: root1234
      
      
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root1234
      POSTGRES_DB: postgres
      PGDATA: /data/postgres
      LISTEN_ADDRESSES: '*'
    volumes:
      - /home/ibrahim/postgres-data/:/data/postgres/
    ports:
      - 5432:5432

  app:
    depends_on:
      - postgres
    build: /home/ibrahim/DevopsProject
    restart: on-failure

    ports:
      - 9090:9090
    
   
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db:
